# These are supported funding model platforms
github: kingebrahimopq-create
patreon: # Replace with your Patreon username
open_collective: # Replace with your Open Collective username
ko_fi: # Replace with your Ko-fi username
tidelift: # Replace with your Tidelift platform-name/package-name e.g., npm/babel
gitcoin: # Replace with your Gitcoin username
custom: ['https://example.com/donate']
