# .github/workflows/windows.yml
name: Build Windows Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Build Web App
      run: npm run build

    - name: Compile Windows Installer
      run: npx electron-builder --win -c electron-builder.json

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v3
      with:
        name: MyLab-Windows-App
        path: dist/**/*.exe
